export const internalException = {
  status: 500,
  message: 'An error has occurred. Please try again later!'
};
